### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by shirshak55** [mtkennerly/shawl#1]
I am using it for node JS express server?

I have tried to use it like this

shawl add --name express -- yarn start

But it doesn't seem to start?

And I think to make it run on startup so I think the best way is to move to startup folder which we can access by shell:startup on run?

**Comment by mtkennerly** [comment]
Hey there! Thanks for trying out Shawl. The issue here is that the default working directory for a Windows service is different than the location of your Express project, so Yarn can't find it. I'll add an option to set the command's working directory for the next release, but in the meantime, you can have Shawl run a script that switches to the right directory. If your Express project is in C:/server, then make a C:/server/run.cmd with this content:

```
cd C:/server
yarn start
```

And then add/start the service with:

```
shawl add --name express -- C:/server/run.cmd
sc start express
```

As for making it run on startup, you should just need to set the `auto` service type:

```
sc config express start= auto
```

**Comment by shirshak55** [comment]
@mtkennerly Hai,


How would I stop or restart the service? I was searching for task manager if process shows but was unable to find it.

**Comment by shirshak55** [comment]
upon investigation i see this message

the service process couldn't connect to service controller :(

**Comment by mtkennerly** [comment]
Did you see that error by directly executing the `shawl run` command configured on the service? That would be expected - it only works when invoked by the Windows service manager itself.

You can get to the services list by clicking on the start menu, typing `services`, and choosing this result to open the services app:

> ![image](https://user-images.githubusercontent.com/4934192/66250671-cb236480-e713-11e9-86ad-915b710ebbb4.png)

I have a suspicion about the remaining issue. I just released v0.4.0 with a `--cwd` option and better error reporting when it can't start the configured command. Could you give it a try and post your shawl.log (from the same folder as shawl.exe)? I suspect you'll see this:

```
2019-10-05 05:52:36 [ INFO] Launching command
2019-10-05 05:52:36 [ERROR] Unable to launch command: The system cannot find the file specified. (os error 2)
```

I've just added a note in the README, but the default service account is Local System, which has a different `PATH` environment variable than your user account does. If Yarn and Node are in your user `PATH`, but not the Local System `PATH`, then it won't be able to find it. To change Local System environment variables:

* Choose this from the start menu:
  > ![image](https://user-images.githubusercontent.com/4934192/66250739-50a71480-e714-11e9-80bf-9f8a6b79bb04.png)
* Click `environment variables`
* Find `PATH` in the `system variables` section
* Might need to reboot after changing it
* Reboot to propagate the change to services ([reference](https://support.microsoft.com/en-us/help/821761/changes-that-you-make-to-environment-variables-do-not-affect-services))

You could probably also change the service to run under your user account (services app -> choose a service -> `properties` -> `log on`).

**Comment by shirshak55** [comment]
@mtkennerly  nope not working it is saying something like this

**Comment by shirshak55** [comment]
@mtkennerly is says error like this

```
C:\Users\s\Desktop\projects\Monitor\main_process\shawl.exe run --name ticketMasterStarter -- yarn --cwd C:\Users\s\Desktop\projects\Monitor\main_process start

Winapi(
    Os {
        code: 1063,
        kind: Other,
        message: "The service process could not connect to the service controlle
r.",
    },
)
```

**Comment by mtkennerly** [comment]
@shirshak55, there should be a log file at `C:\Users\s\Desktop\projects\Monitor\main_process\shawl.log` (same folder as shawl.exe). Could you please post it here? I need to see the full log to investigate this.

For the record, if you try to directly execute `shawl run` in a console as it looks like in that last comment, it will fail 100% of the time, since it has to be executed specially by Windows as part of service startup.

**Comment by mtkennerly** [comment]
@shirshak55 Absolutely, although there's one caveat - see below. This will do exactly what you'd expect, assuming you have a `yarn.cmd` file (I installed Yarn with [Scoop](https://scoop.sh), so I'm not sure if all copies have it):

```
shawl add --name express -- "C:/Program Files (x86)/Yarn/bin/yarn.cmd" --cwd "C:/Users/s/Desktop/projects/Monitor/main_process" start
```

The one caveat is that if `yarn start` runs `node index.js`, then you may have the same problem with it not finding Node. That's why I think adding it to the system `PATH` (and/or changing the service user) is probably easier overall.

**Comment by shirshak55** [comment]
@mtkennerly lol it was node. I tried adding yarn to path etc.... all that was due to path problem. I

Thanks.

**Comment by shirshak55** [comment]
@mtkennerly thanks again. I wished there was some indication like node not found so we can easily check.
