### ISSUE TITLE
Command line parser error if cwd on Windows ends with backslash

### ISSUE THREAD

**Issue by schlamar** [mtkennerly/shawl#59]
```
>shawl --version
shawl 1.6.0
>shawl run --cwd "C:\Program Files\" -- server.exe
error: the following required arguments were not provided:
  <COMMAND>...

Usage: shawl run --cwd <path> -- <COMMAND>...

For more information, try '--help'.

```

**Comment by mtkennerly** [comment]
Hi! Interestingly, I can reproduce this with Command Prompt, but not with PowerShell.

I added `println!("{:?}", std::env::args());` in `main` (to rule out anything to do with Clap's parsing), and this is what I see:

* Original input: `.\target\debug\shawl.exe add --name shawl --cwd "C:\tmp\" -- foo`
* Output in Command Prompt: `[".\\target\\debug\\shawl.exe", "add", "--name", "shawl", "--cwd", "C:\\tmp\" -- foo"]`
* Output in PowerShell: `["C:\\git\\shawl\\target\\debug\\shawl.exe", "add", "--name", "shawl", "--cwd", "C:\\tmp\\", "--", "foo"]`

I can also reproduce the same thing with a basic C program. From some research, it sounds like this is an intentional behavior. Microsoft [has a page](https://learn.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments) that confirms:

> A double quote mark preceded by a backslash (`\"`) is interpreted as a literal double quote mark (`"`).

I don't think there's anything I can do here, unfortunately.
